---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-feature-discovery
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  selector:
    matchLabels:
      app: node-feature-discovery
  template:
    metadata:
      labels:
        app: node-feature-discovery
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/kubernetes_incubator/node-feature-discovery:v0.1.0
        name: node-feature-discovery
        args:
        - "--sleep-interval=60s"
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-sys
            mountPath: /host-sys 
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
