---
- name: copy create-nvidia-namespace.yaml up to master
  copy:
    src: create-nvidia-namespace.yaml
    dest: /tmp/create-nvidia-namespace.yaml
  delegate_to: "{{ master_hostname }}"

- name: create nvidia namespace
  shell: oc create -f /tmp/create-nvidia-namespace.yaml
  delegate_to: "{{ master_hostname }}"

- name: copy device-plugin yaml for use by oc
  copy:
    src: nvidia-device-plugin-centos.yml
    dest: /tmp/nvidia-device-plugin-centos.yml

- name: install the NVIDIA kubernetes device-plugin (CentOS base image)
  shell:  oc create -f /tmp/nvidia-device-plugin-centos.yml
